import * as ast from '../../generated/ast.js';
import { baseTypeReference, type DevmType } from '../../typesystem.js';
import { cppTypeOfReference, isCppType } from '../../cpp-types.js';
import type { CppResolvedType } from '../../cpp-header/model.js';

/** C++ keywords and alternative tokens (and a few names that should not be redefined). */
export const CPP_KEYWORDS: ReadonlySet<string> = new Set([
    'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor', 'bool', 'break', 'case', 'catch', 'char',
    'char8_t', 'char16_t', 'char32_t', 'class', 'compl', 'concept', 'const', 'consteval', 'constexpr', 'constinit',
    'const_cast', 'continue', 'co_await', 'co_return', 'co_yield', 'decltype', 'default', 'delete', 'do', 'double',
    'dynamic_cast', 'else', 'enum', 'explicit', 'export', 'extern', 'false', 'float', 'for', 'friend', 'goto', 'if',
    'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept', 'not', 'not_eq', 'nullptr', 'operator', 'or',
    'or_eq', 'private', 'protected', 'public', 'register', 'reinterpret_cast', 'requires', 'return', 'short', 'signed',
    'sizeof', 'static', 'static_assert', 'static_cast', 'struct', 'switch', 'template', 'this', 'thread_local', 'throw',
    'true', 'try', 'typedef', 'typeid', 'typename', 'union', 'unsigned', 'using', 'virtual', 'void', 'volatile',
    'wchar_t', 'while', 'xor', 'xor_eq', 'final', 'override', 'import', 'module',
    'NULL', 'main', 'errno', 'assert', 'std', 'sc'
]);

/** Names generated members must not use: the C++ keywords and the names of parameters and members of the generated code. */
export const CPP_RESERVED_NAMES: ReadonlySet<string> = new Set([...CPP_KEYWORDS, 'value', 'machine', 'owner', 'callback', 'operationCallback']);

/** C++ type of a value type (C++ enum / struct / array types: their qualified name). */
export function cppType(type: DevmType): string {
    if (isCppType(type)) {
        return type.cppName;
    }
    switch (type) {
        case 'real': return 'sc::real';
        case 'boolean': return 'sc::boolean';
        case 'string': return 'sc::string';
        case 'void': return 'void';
        default: return 'sc::integer';
    }
}

/** Type of a parameter of a generated function (strings, structs and arrays by const reference). */
export function cppParameterType(type: DevmType, spelling = cppType(type)): string {
    return type === 'string' || (isCppType(type) && type.kind !== 'enum') ? `const ${spelling}&` : spelling;
}

/** Names of `<cstdint>` / `<cstddef>` typedefs, which are written with `std::` in generated code. */
const STD_TYPEDEF = /^(u?int(_least|_fast)?(8|16|32|64)_t|u?intmax_t|u?intptr_t|size_t|ptrdiff_t)$/;

/** The spelling of a C++ type in generated code (`uint8_t` -> `std::uint8_t`). */
export function cppSpelling(type: CppResolvedType): string {
    return STD_TYPEDEF.test(type.cppName) ? `std::${type.cppName}` : type.cppName;
}

/**
 * The C++ type of a declaration with the given type reference: the name of an imported C++ type as
 * written in the model (`motor::Rpm`, `::Color`; through aliases of the model), `std::uint8_t` for `<cstdint>`
 * typedefs, otherwise the C++ type of the model type ({@link cppType}).
 */
export function cppDeclaredType(reference: ast.TypeReference | undefined, type: DevmType): string {
    const base = baseTypeReference(reference);
    const cpp = base ? cppTypeOfReference(base) : undefined;
    if (base && cpp && !cpp.mapping.error) {
        return cpp.declaration ? base.name.replace(/\s+/g, '') : cppSpelling(cpp.resolved);
    }
    return cppType(type);
}

/** C++ literal of the default value of a type. */
export function cppDefault(type: DevmType): string {
    if (isCppType(type)) {
        return `${type.cppName}{}`;
    }
    switch (type) {
        case 'real': return '0.0';
        case 'boolean': return 'false';
        case 'string': return '""';
        default: return '0';
    }
}

/** A `//` comment (a trailing backslash would continue the comment on the next line). */
export function lineComment(text: string): string {
    return `// ${text.endsWith('\\') ? `${text} .` : text}`;
}

/** Name of the runtime header shared by all generated state machines. */
export const RUNTIME_HEADER = 'sc_statemachine.h';

/** Content of `sc_statemachine.h`: basic types and interfaces, like `sc_types.h` / `sc_statemachine.h` of itemis CREATE. */
export const RUNTIME_HEADER_CONTENT = `// Runtime of the C++ state machines generated by devm (Device Modeler): basic types and interfaces.
// Shared by all generated state machines; C++11 or later.
#ifndef SC_STATEMACHINE_H_
#define SC_STATEMACHINE_H_

#include <cstdint>
#include <cstdlib>
#include <stdexcept>
#include <string>

namespace sc {

using integer = std::int64_t;
using real = double;
using boolean = bool;
using string = std::string;

/** Identifies a time event of a state machine (passed to the timer service). */
using eventid = int;

/** Kinds of runtime errors (docs/semantics.md). */
enum class ErrorKind {
    DivisionByZero,      // integer division or modulo by zero
    ShiftOutOfRange,     // shift amount outside of 0..63
    InvalidConversion,   // conversion of a non-finite real to integer
    NoEnabledTransition, // choice, entry point or exit node without enabled transition
    NoInitialTransition, // composite state entered by default without initial transition
    InvalidTime,         // period of an 'every' time event is not positive
    Loop,                // too many transitions in one step or too many queued event steps
    IndexOutOfBounds     // element access outside of the bounds of an array
};

/**
 * Runtime error of a state machine (thrown if no error handler is set). The step in which the error
 * occurred is aborted; the state machine stays usable, but its configuration may be inconsistent.
 */
class StatemachineError : public std::runtime_error {
public:
    StatemachineError(ErrorKind kind, const std::string& message) : std::runtime_error(message), errorKind(kind) {}

    ErrorKind kind() const noexcept {
        return errorKind;
    }

private:
    ErrorKind errorKind;
};

/**
 * Receives the runtime errors of a state machine instead of exceptions (setErrorHandler()), e.g. for
 * code compiled without exceptions. After onError() returns, the state machine continues with the
 * failed part skipped (a division by zero yields 0, a choice without enabled branch is not left, ...).
 */
class ErrorHandler {
public:
    virtual ~ErrorHandler() = default;
    virtual void onError(ErrorKind kind, const std::string& message) = 0;
};

namespace detail {

/** Throws a StatemachineError (aborts the program if exceptions are disabled). */
[[noreturn]] inline void throwError(ErrorKind kind, const std::string& message) {
#if defined(__cpp_exceptions) || defined(__EXCEPTIONS) || defined(_CPPUNWIND)
    throw StatemachineError(kind, message);
#else
    (void)kind;
    (void)message;
    std::abort();
#endif
}

} // namespace detail

/** Basic interface of all state machines. */
class StatemachineInterface {
public:
    virtual ~StatemachineInterface() = default;
    /** Enters the state machine: initializes the variables and enters the initial states. */
    virtual void enter() = 0;
    /** Exits the state machine (exit reactions of all active states). */
    virtual void exit() = 0;
    /** Cycle based: one run cycle with all events raised since the previous cycle. Event driven: a step without events. */
    virtual void runCycle() = 0;
    /** Whether the state machine has been entered and not exited. */
    virtual bool isActive() const = 0;
    /** Whether the state machine is final (the final state of its top-level region is active). */
    virtual bool isFinal() const = 0;
};

class TimedInterface;

/**
 * Timer service, implemented by the host: starts and stops the timers of time events. When a timer
 * expires, the host calls statemachine->raiseTimeEvent(event).
 */
class TimerServiceInterface {
public:
    virtual ~TimerServiceInterface() = default;
    /** Starts (or restarts) a timer that expires after durationNs nanoseconds (periodic: every durationNs). */
    virtual void setTimer(TimedInterface* statemachine, eventid event, integer durationNs, bool periodic) = 0;
    /** Stops a timer. */
    virtual void unsetTimer(TimedInterface* statemachine, eventid event) = 0;
};

/** Interface of state machines with time events. */
class TimedInterface {
public:
    virtual ~TimedInterface() = default;
    virtual void setTimerService(TimerServiceInterface* timerService) = 0;
    virtual TimerServiceInterface* getTimerService() = 0;
    /** Called by the timer service when the timer of a time event expires. */
    virtual void raiseTimeEvent(eventid event) = 0;
    /** Number of time events; their ids are 0 .. getNumberOfParallelTimeEvents() - 1. */
    virtual integer getNumberOfParallelTimeEvents() const = 0;
};

namespace rx {

template <typename T> class Observer;
template <typename T> class Observable;

namespace detail {

template <typename T> class ObserverList;

/** Link of an observer in the list of its observable (no dynamic memory). */
template <typename T>
class ObserverLink {
public:
    ObserverLink() = default;
    ObserverLink(const ObserverLink&) = delete;
    ObserverLink& operator=(const ObserverLink&) = delete;

    /** Whether the observer is subscribed to an observable. */
    bool isSubscribed() const {
        return list != nullptr;
    }

protected:
    ~ObserverLink() {
        if (list != nullptr) {
            list->remove(this);
        }
    }

private:
    friend class ObserverList<T>;
    ObserverList<T>* list = nullptr;
    ObserverLink* nextLink = nullptr;
};

/** The observers of an observable in subscription order. */
template <typename T>
class ObserverList {
public:
    ObserverList() = default;
    ObserverList(const ObserverList&) = delete;
    ObserverList& operator=(const ObserverList&) = delete;

    ~ObserverList() {
        for (ObserverLink<T>* link = first; link != nullptr; link = link->nextLink) {
            link->list = nullptr;
        }
    }

    /** Subscribes an observer; false if it is already subscribed (an observer observes one observable at a time). */
    bool subscribe(Observer<T>& observer) {
        ObserverLink<T>* link = &observer;
        if (link->list != nullptr) {
            return false;
        }
        link->list = this;
        link->nextLink = nullptr;
        ObserverLink<T>** end = &first;
        while (*end != nullptr) {
            end = &(*end)->nextLink;
        }
        *end = link;
        return true;
    }

    /** Unsubscribes an observer; false if it is not subscribed to this observable. */
    bool unsubscribe(Observer<T>& observer) {
        ObserverLink<T>* link = &observer;
        if (link->list != this) {
            return false;
        }
        remove(link);
        return true;
    }

protected:
    template <typename F>
    void forEach(F notify) const {
        ObserverLink<T>* link = first;
        while (link != nullptr) {
            ObserverLink<T>* next = link->nextLink;
            notify(*static_cast<Observer<T>*>(link));
            link = next;
        }
    }

private:
    friend class ObserverLink<T>;

    void remove(ObserverLink<T>* link) {
        for (ObserverLink<T>** p = &first; *p != nullptr; p = &(*p)->nextLink) {
            if (*p == link) {
                *p = link->nextLink;
                break;
            }
        }
        link->list = nullptr;
        link->nextLink = nullptr;
    }

    ObserverLink<T>* first = nullptr;
};

} // namespace detail

/** Observer of an out event with a value of type T (the observer is unsubscribed when it is destroyed). */
template <typename T>
class Observer : public detail::ObserverLink<T> {
public:
    virtual ~Observer() = default;
    virtual void next(const T& value) = 0;
};

/** Observer of an out event without value. */
template <>
class Observer<void> : public detail::ObserverLink<void> {
public:
    virtual ~Observer() = default;
    virtual void next() = 0;
};

/** Out event of a state machine that observers subscribe to. */
template <typename T>
class Observable : public detail::ObserverList<T> {
public:
    /** Notifies all observers (called by the state machine). */
    void next(const T& value) const {
        this->forEach([&value](Observer<T>& observer) { observer.next(value); });
    }
};

template <>
class Observable<void> : public detail::ObserverList<void> {
public:
    /** Notifies all observers (called by the state machine). */
    void next() const {
        this->forEach([](Observer<void>& observer) { observer.next(); });
    }
};

} // namespace rx

} // namespace sc

#endif // SC_STATEMACHINE_H_
`;
