// Enumerator values computed by the header analyzer (test/cpp-enum-values.test.ts). Every value is
// also checked by a C++ compiler (static_assert generated by the test), so this header must compile.
#pragma once
#include <cstdint>

#define DEV_BASE 0x40
#define BIT(n) (1u << (n))

namespace ev {

constexpr int kOffset = 100;
const unsigned kCount = 3u;

enum class Other : std::uint8_t { V = 9, W };
enum Plain { P0, P1 = 7 };

/// Implicit numbering: first 0, then previous + 1, also after explicit and negative values.
enum Implicit { I0, I1, I2, I10 = 10, I11, I12, INeg = -2, INeg1, INeg0, IZero = 0, IOne };

/// Integer literals.
enum Literals : long long {
    Dec = 42, Hex = 0x2A, HexUpper = 0XFF, Oct = 010, OctMax = 0777, Zero = 0, Bin = 0b1010, BinUpper = 0B11,
    Sep = 1'000'000, SepHex = 0xFF'FF, SepBin = 0b1111'0000,
    SufU = 7u, SufL = 8l, SufLL = 9LL, SufUL = 10ul, SufULL = 11ULL, SufLU = 12lu, SufLLU = 13llu,
    True = true, False = false
};

/// Character literals.
enum Chars {
    CharA = 'A', CharNl = '\n', CharTab = '\t', CharHex = '\x41', CharOct = '\101', CharNul = '\0',
    CharBackslash = '\\', CharQuote = '\'', CharU8 = u8'a', CharU16 = u'ä', CharU32 = U'\U0001F600',
    CharWide = L'z', CharNext
};

/// Operators with C++ precedence, associativity and truncating division.
enum Ops {
    Add = 1 + 2 * 3, Paren = (1 + 2) * 3, Sub = 10 - 3 - 2, Div = 7 / 2, DivNeg = -7 / 2, DivNeg2 = 7 / -2,
    Mod = 7 % 3, ModNeg = -7 % 3, ModNeg2 = 7 % -3, Shl = 1 << 4, Shr = 256 >> 3, ShrNeg = -16 >> 2,
    ShiftPrec = 1 << 2 + 1, BitPrec = 1 | 2 ^ 3 & 4, Compl = ~0, Not = !0, NotNot = !!5, Neg = -(3), Plus = +4,
    Lt = 3 < 4, Ge = 3 >= 4, Eq = 2 + 2 == 4, Ne = 1 != 1, And = 6 & 3, Or = 6 | 3, Xor = 6 ^ 3,
    LAnd = 1 && 0, LOr = 0 || 2, Tern = 2 > 1 ? 20 : 30, TernNested = 0 ? 1 : 0 ? 2 : 3, CmpChain = 1 < 2 == 1,
    UnsignedCmp = -1 < 0u, UnsignedDiv = (0u - 1) / 2
};

/// References to enumerators, constants and macros.
enum Refs {
    RA = 1, RB = 2, RMask = RA | RB, RLast = RMask, RCount,
    ROther = static_cast<int>(Other::V), RCast = (int)Other::W, RPlain = P1 + 1, RPlainQ = Plain::P1 * 2,
    RConst = kOffset + 1, RConstU = kCount, RMacro = DEV_BASE + 1, RFunc = BIT(3),
    RSize = sizeof(std::uint32_t), RSizeE = sizeof(Other), RIn = RA + RLast
};

/// Flags with a fixed unsigned underlying type.
enum class Flags : std::uint32_t {
    None, Read = BIT(0), Write = BIT(1), Exec = BIT(2), All = Read | Write | Exec, Mask = ~0u, High = 0x80000000
};

/// Fixed underlying types of all sizes (std:: and global typedef names).
enum class Small : std::uint8_t { Min = 0, Max = 255 };
enum class Signed8 : std::int8_t { Lo = -128, Hi = 127, MinusOne = -1 };
enum Short : int16_t { S0 = -300, S1 };
enum class Wide : std::uint64_t {
    Big = 0xFFFFFFFFFFFFFFFFull, Top = 1ull << 63, Precise = 9007199254740993ull, Next = 9007199254740992ull, Next1
};
enum class WideSigned : std::int64_t { Min = -9223372036854775807LL - 1, Max = 9223372036854775807LL };

/// Without fixed underlying type the values decide the type (also of implicit successors).
enum Unfixed { U0 = 0xFFFFFFFF, U1 };
/// Inside the enum body an enumerator has the type of its initializer: IB0 is an unsigned int.
enum InBody { IB0 = 0u - 1, IB1 = IB0 + 1 };

/// C style flags.
typedef enum { C_A = 1 << 0, C_B = 1 << 1, C_AB = C_A | C_B } c_flags_t;

}  // namespace ev
