// Builds the extension: the extension host bundle (CJS), the language server (CJS) and the diagram
// webview (IIFE, Vite). The TextMate grammars and the generator configuration schema are copied from
// the language package.
// Usage: node scripts/build.mjs [--watch]
import * as esbuild from 'esbuild';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { bundleOptions, root } from './bundles.mjs';

const watch = process.argv.includes('--watch');

// the TextMate grammars generated by langium (packages/language/syntaxes)
await fs.mkdir(path.join(root, 'syntaxes'), { recursive: true });
for (const grammar of ['devm.tmLanguage.json', 'devmtest.tmLanguage.json']) {
    await fs.copyFile(path.join(root, '../language/syntaxes', grammar), path.join(root, 'syntaxes', grammar));
}
// the JSON schema of generator configurations (devm.gen.json, `jsonValidation`) and the license
await fs.mkdir(path.join(root, 'schemas'), { recursive: true });
await fs.copyFile(path.join(root, '../language/schemas/devm-gen.schema.json'), path.join(root, 'schemas/devm-gen.schema.json'));
await fs.copyFile(path.join(root, '../../LICENSE'), path.join(root, 'LICENSE'));

const builds = [bundleOptions('extension', { minify: !watch }), bundleOptions('server', { minify: !watch })];

if (watch) {
    for (const options of builds) {
        const context = await esbuild.context(options);
        await context.watch();
    }
    console.log('watching extension and server (run `vite build --config vite.webview.config.ts --watch` for the webview)');
} else {
    await Promise.all(builds.map(options => esbuild.build(options)));
    const { build } = await import('vite');
    await build({ configFile: path.join(root, 'vite.webview.config.ts'), root, logLevel: 'warn' });
    console.log('built dist/extension.cjs, dist/server.cjs and dist/webview/');
}
