// Builds the extension: the extension host bundle (CJS), the language server (CJS) and the diagram
// webview (IIFE, Vite). The TextMate grammars are copied from the language package.
// Usage: node scripts/build.mjs [--watch]
import * as esbuild from 'esbuild';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const watch = process.argv.includes('--watch');

// the TextMate grammars generated by langium (packages/language/syntaxes)
await fs.mkdir(path.join(root, 'syntaxes'), { recursive: true });
for (const grammar of ['hsm.tmLanguage.json', 'hsmtest.tmLanguage.json']) {
    await fs.copyFile(path.join(root, '../language/syntaxes', grammar), path.join(root, 'syntaxes', grammar));
}

/** @type {esbuild.BuildOptions} */
const common = {
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node20',
    sourcemap: true,
    minify: !watch,
    // the language package is bundled from its TypeScript sources (no pre-build needed)
    alias: { 'hsm-language': path.join(root, '../language/src/index.ts') },
    external: ['vscode'],
    logLevel: 'info',
    tsconfig: path.join(root, 'tsconfig.json')
};

const builds = [
    { ...common, entryPoints: { extension: path.join(root, 'src/extension/extension.ts') }, outExtension: { '.js': '.cjs' }, outdir: path.join(root, 'dist') },
    { ...common, entryPoints: { server: path.join(root, 'src/server/main.ts') }, outExtension: { '.js': '.cjs' }, outdir: path.join(root, 'dist') }
];

if (watch) {
    for (const options of builds) {
        const context = await esbuild.context(options);
        await context.watch();
    }
    console.log('watching extension and server (run `vite build --config vite.webview.config.ts --watch` for the webview)');
} else {
    await Promise.all(builds.map(options => esbuild.build(options)));
    const { build } = await import('vite');
    await build({ configFile: path.join(root, 'vite.webview.config.ts'), root, logLevel: 'warn' });
    console.log('built dist/extension.cjs, dist/server.cjs and dist/webview/');
}
